





export const schema1 = {
  PataNum: { path: "patient.member_id", default: 0 },
  LName: { path: "patient.last_name", default: "" },
  FName: { path: "patient.first_name", default: "" },
  MiddleI: { path: "patient.middle_name", default: "" },
  Preferred: { path: "patient.name", default: "" },
  PatStatus: { path: "patient.is_subscriber", default: 1 },
  Gender: { path: "patient.gender", default: 0 },
  Position: { path: "", default: 0 },
  Birthdate: { path: "patient.dob", default: "" },
  SSN: { path: "", default: "" },
  Address: { path: "patient.address.street1", default: "" },
  Address2: { path: "patient.address.street2", default: "" },
  City: { path: "patient.address.city", default: "" },
  State: { path: "patient.address.state", default: "" },
  Zip: { path: "patient.address.zip", default: "" },
  HmPhone: { path: "patient.metadata[0].value", default: "" },
  WkPhone: { path: "patient.metadata[1].value", default: "" },
  WirelessPhone: { path: "patient.metadata[2].value", default: "" },
  Guarantor: { path: "subscriber.member_id", default: "" },
  CreditType: { path: "", default: "" },
  Email: { path: "patient.metadata[3].value", default: "" },
  Salutation: { path: "", default: "" },
  EstBalance: { path: "", default: 0 },
  PriProv: { path: "provider.first_name + ' ' +  provider.last_name", default: "" },
  SecProv: { path: "", default: "" },
  FeeSched: { path: "", default: "" },
  BillingType: { path: "", default: "" },
  ImageFolder: { path: "", default: "" },
  AddrNote: { path: "", default: "" },
  FamFinUrgNote: { path: "", default: "" },
  MedUrgNote: { path: "", default: "" },
  ApptModNote: { path: "", default: "" },
  StudentStatus: { path: "", default: "" },
  SchoolName: { path: "", default: "" },
  ChartNumber: { path: "", default: "" },
  MedicaidID: { path: "patient.member_id", default: "" },
  Bal_0_30: { path: "", default: 0 },
  Bal_31_60: { path: "", default: 0 },
  Bal_61_90: { path: "", default: 0 },
  BalOver90: { path: "", default: 0 },
  InsEst: { path: "", default: 0 },
  BalTotal: { path: "", default: 0 },
  EmployerNum: { path: "", default: 0 },
  EmploymentNote: { path: "", default: "" },
  County: { path: "", default: "" },
  GradeLevel: { path: "", default: "" },
  Urgency: { path: "", default: 0 },
  DateFirstVisit: { path: "", default: "" },
  ClinicNum: { path: "", default: 0 },
  HasIns: { path: "patient.coverage.status", default: false },
  TrophyFolder: { path: "", default: "" },
  PlannedIsDone: { path: "", default: false },
  Premed: { path: "", default: false },
  Ward: { path: "", default: "" },
  PreferConfirmMethod: { path: "", default: 0 },
  PreferContactMethod: { path: "", default: 0 },
  PreferRecallMethod: { path: "", default: 0 },
  SchedBeforeTime: { path: "", default: "" },
  SchedAfterTime: { path: "", default: "" },
  SchedDayOfWeek: { path: "", default: 0 },
  Language: { path: "", default: "" },
  AdmitDate: { path: "", default: "" },
  Title: { path: "", default: "" },
  PayPlanDue: { path: "", default: 0 },
  SiteNum: { path: "", default: 0 },
  DateTStamp: { path: "", default: "" },
  ResponsParty: { path: "", default: 0 },
  CanadianEligibilityCode: { path: "", default: 0 },
  AskToArriveEarly: { path: "", default: false },
  PreferContactConfidential: { path: "", default: false },
  SuperFamily: { path: "", default: 0 },
  TxtMsgOk: { path: "", default: false },
  SmokingSnoMed: { path: "", default: "" },
  Country: { path: "patient.address.country", default: "" },
  DateTimeDeceased: { path: "", default: "" },
  BillingCycleDay: { path: "", default: 0 },
  SecUserNumEntry: { path: "", default: 0 },
  SecDateEntry: { path: "", default: "" },
  HasSuperBilling: { path: "", default: false },
  PatNumCloneFrom: { path: "", default: 0 },
  DiscountPlanNum: { path: "", default: 0 },
  HasSignedTil: { path: "", default: false },
  ShortCodeOptIn: { path: "", default: false },
  SecurityHash: { path: "", default: "" },
  PatPlanNum: { path: "", default: 0 },
  PatNum1: { path: "", default: 0 },
  Ordinal: { path: "", default: 0 },
  IsPending: { path: "", default: false },
  Relationship: { path: "patient.relationship", default: "" },
  PatID: { path: "patient.member_id", default: "" },
  InsSubNum: { path: "", default: 0 },
  OrthoAutoFeeBilledOverride: { path: "", default: 0 },
  OrthoAutoNextClaimDate: { path: "", default: "" },
  SecDateTEntry: { path: "", default: "" },
  SecDateTEdit: { path: "", default: "" },
  PlanNum: { path :[ "plan.plan_id","plan.number"] , default: 0 },
  Subscriber: { path: "subscriber.member_id", default: "" },
  DateEffective: { 
    path: ["plan.effective_date", "patient.coverage.effective_date"], 
    default: ""
  },
  SubscriberID: { path: "subscriber.member_id", default: "" },
  GroupNum: { path: "plan.group_number", default: "" },
  GroupName: { path: "plan.group_name", default: "" },
  CarrierNum: { path: "payer.id", default: "" },
  CarrierNum1: { path: "", default: "" },
  CarrierName: { path: "payer.name", default: "" },
  carrierPhone: { path: "payer.phone", default: "" },
  ElectID: { path :[ "payer.electronic_id" ,"payer.id"], default: "" }
};


